name: CI

on:
    push:
        branches: [ "master" ]
    pull_request:
        branches: [ "master" ]

permissions:
    contents: read
    packages: write

jobs:
    build-and-lint:
        uses: GEWIS/actions/.github/workflows/lint-and-build-yarn.yml@v1
        with:
            working-directory: ./backend
            node-version: '22.x'
            format: true
            lint: true
            build: true
            test: false
